import { defineConfig } from "@playwright/test";
import { defineBddConfig } from "playwright-bdd";

/**
 * Playwright configuration for Magenta IDE E2E tests.
 *
 * Two projects:
 *  - "bdd" — BDD/Cucumber scenarios generated by playwright-bdd
 *  - "smoke" — existing smoke tests in tests/
 */

const bddTestDir = defineBddConfig({
  features: "features/**/*.feature",
  steps: ["steps/**/*.steps.ts", "support/bdd-fixtures.ts"],
  outputDir: ".features-gen",
});

export default defineConfig({
  timeout: 60_000,
  expect: { timeout: 10_000 },
  fullyParallel: false,
  workers: 1,
  reporter: [["list"], ["html", { open: "never", outputFolder: "playwright-report" }]],
  outputDir: "test-results",
  use: {
    trace: "retain-on-failure",
    video: "retain-on-failure",
    screenshot: "only-on-failure",
  },
  projects: [
    {
      name: "bdd",
      testDir: bddTestDir,
    },
    {
      name: "smoke",
      testDir: "./tests",
    },
  ],
});
