import { z } from "zod";
import { MAIN_TABS, PIPELINE_STAGES, REPO_STATUSES, STAGE_STATUSES } from "./constants";
import { MagentaConfigSchema } from "./config";
import { AI_PROVIDERS, AI_SESSION_STATUSES, AISessionRecordSchema, ProviderMetaSchema } from "./aiTerminal";

export const RepositorySchema = z.object({
  id: z.string(),
  name: z.string(),
  path: z.string(),
  branch: z.string(),
  hasSpecs: z.boolean(),
  specCount: z.number().int().nonnegative(),
  status: z.enum(REPO_STATUSES),
  scannedAt: z.number().int().nonnegative(),
  createdAt: z.number().int().nonnegative(),
});

export const PipelineStageSchema = z.object({
  name: z.enum(PIPELINE_STAGES),
  status: z.enum(STAGE_STATUSES),
  filePath: z.string().nullable(),
  metadata: z
    .object({
      taskCount: z.number().int().nonnegative().optional(),
      completedCount: z.number().int().nonnegative().optional(),
      worktreeCount: z.number().int().nonnegative().optional(),
      implementationProgress: z.number().min(0).max(100).optional(),
      approvedBy: z.string().optional(),
      approvedAt: z.string().optional(),
    })
    .optional(),
});

export const SpecFolderSchema = z.object({
  id: z.string(),
  repoPath: z.string(),
  name: z.string(),
  path: z.string(),
  branch: z.string().optional(),
  isCurrentBranch: z.boolean().optional(),
  stages: z.array(PipelineStageSchema),
  files: z.array(z.string()),
  createdAt: z.number().int().nonnegative(),
});

export const SessionStateSchema = z.object({
  selectedRepoPath: z.string().nullable(),
  selectedSpecPath: z.string().nullable(),
  selectedFilePath: z.string().nullable(),
  sidebarWidth: z.number().int().positive().nullable(),
  activityPanelWidth: z.number().int().positive().nullable(),
  activityPanelOpen: z.boolean(),
  sidebarCollapsed: z.boolean(),
  activityCollapsed: z.boolean(),
  specPanelHeight: z.number().int().positive().nullable(),
  mainTab: z.enum(MAIN_TABS),
  updatedAt: z.number().int().nonnegative(),
});

export const IpcRequestSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("repo:list") }),
  z.object({ type: z.literal("repo:scan") }),
  z.object({ type: z.literal("spec:list"), repoPath: z.string() }),
  z.object({ type: z.literal("file:read"), filePath: z.string() }),
  z.object({ type: z.literal("file:write"), filePath: z.string(), content: z.string() }),
  z.object({ type: z.literal("dir:list"), dirPath: z.string() }),
  z.object({ type: z.literal("session:get") }),
  z.object({ type: z.literal("session:update"), state: SessionStateSchema.partial() }),
  z.object({ type: z.literal("config:get") }),
  z.object({ type: z.literal("config:add-working-dir"), path: z.string() }),
  z.object({ type: z.literal("config:remove-working-dir"), path: z.string() }),
  z.object({ type: z.literal("config:update"), config: z.record(z.string(), z.unknown()) }),
  z.object({ type: z.literal("branch:list"), repoPath: z.string() }),
  z.object({ type: z.literal("branch:checkout"), repoPath: z.string(), branch: z.string() }),
  z.object({ type: z.literal("gitfile:read"), repoPath: z.string(), ref: z.string(), relativePath: z.string() }),
  z.object({ type: z.literal("worktree:create"), repoPath: z.string(), branch: z.string(), name: z.string() }),
  z.object({ type: z.literal("worktree:list"), repoPath: z.string().optional() }),
  z.object({ type: z.literal("repo:onboard"), repoPath: z.string(), aiAgent: z.string(), useWorktree: z.boolean().optional() }),
  z.object({ type: z.literal("repo:upgrade-specify"), repoPath: z.string() }),
  z.object({ type: z.literal("repo:onboard:cancel"), repoPath: z.string() }),
  z.object({ type: z.literal("repo:force-reload"), repoPath: z.string() }),
  z.object({ type: z.literal("git:user"), repoPath: z.string() }),
  z.object({ type: z.literal("worktree:status"), repoPath: z.string(), worktreePath: z.string() }),
  z.object({ type: z.literal("worktree:merge"), repoPath: z.string(), worktreePath: z.string(), worktreeBranch: z.string(), targetBranch: z.string() }),
  z.object({ type: z.literal("worktree:branches"), repoPath: z.string() }),
  z.object({ type: z.literal("worktree:delete"), repoPath: z.string(), worktreePath: z.string() }),
  z.object({ type: z.literal("terminal:spawn"), cwd: z.string(), cols: z.number().int().positive(), rows: z.number().int().positive() }),
  z.object({ type: z.literal("terminal:input"), sessionId: z.string(), data: z.string() }),
  z.object({ type: z.literal("terminal:resize"), sessionId: z.string(), cols: z.number().int().positive(), rows: z.number().int().positive() }),
  z.object({ type: z.literal("terminal:close"), sessionId: z.string() }),
  z.object({ type: z.literal("ai-session:create"), provider: z.enum(AI_PROVIDERS), repoPath: z.string().optional(), branch: z.string().optional(), worktreePath: z.string().optional(), args: z.array(z.string()).optional(), cols: z.number().int().positive(), rows: z.number().int().positive() }),
  z.object({ type: z.literal("ai-session:resume"), sessionId: z.string(), cols: z.number().int().positive(), rows: z.number().int().positive() }),
  z.object({ type: z.literal("ai-session:input"), sessionId: z.string(), data: z.string() }),
  z.object({ type: z.literal("ai-session:resize"), sessionId: z.string(), cols: z.number().int().positive(), rows: z.number().int().positive() }),
  z.object({ type: z.literal("ai-session:stop"), sessionId: z.string() }),
  z.object({ type: z.literal("ai-session:list") }),
  z.object({ type: z.literal("ai-session:delete"), sessionId: z.string() }),
  z.object({ type: z.literal("ai-session:providers") }),
]);

export const IpcResponseSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("repo:list:result"), repos: z.array(RepositorySchema) }),
  z.object({ type: z.literal("repo:scan:started") }),
  z.object({
    type: z.literal("repo:scan:progress"),
    scanned: z.number().int().nonnegative(),
    total: z.number().int().nonnegative(),
    currentDir: z.string(),
  }),
  z.object({
    type: z.literal("repo:scan:complete"),
    repos: z.array(RepositorySchema),
    added: z.number().int().nonnegative(),
    updated: z.number().int().nonnegative(),
    missing: z.number().int().nonnegative(),
  }),
  z.object({ type: z.literal("spec:list:result"), repoPath: z.string(), specs: z.array(SpecFolderSchema) }),
  z.object({ type: z.literal("spec:sync:started"), repoPath: z.string() }),
  z.object({ type: z.literal("spec:sync:complete"), repoPath: z.string() }),
  z.object({ type: z.literal("session:response"), state: SessionStateSchema }),
  z.object({ type: z.literal("session:updated") }),
  z.object({ type: z.literal("config:response"), config: MagentaConfigSchema }),
  z.object({ type: z.literal("config:updated"), config: MagentaConfigSchema }),
  z.object({ type: z.literal("file:read:result"), filePath: z.string(), content: z.string() }),
  z.object({ type: z.literal("file:write:result"), filePath: z.string(), success: z.boolean() }),
  z.object({
    type: z.literal("dir:list:result"),
    dirPath: z.string(),
    entries: z.array(z.object({ name: z.string(), path: z.string(), isDirectory: z.boolean() })),
  }),
  z.object({ type: z.literal("branch:list:result"), repoPath: z.string(), branches: z.array(z.string()), current: z.string() }),
  z.object({ type: z.literal("branch:checkout:result"), repoPath: z.string(), branch: z.string(), success: z.boolean() }),
  z.object({ type: z.literal("gitfile:read:result"), filePath: z.string(), content: z.string() }),
  z.object({ type: z.literal("worktree:create:result"), repoPath: z.string(), worktreePath: z.string(), branch: z.string(), success: z.boolean() }),
  z.object({
    type: z.literal("worktree:list:result"),
    worktrees: z.array(z.object({
      repoPath: z.string(),
      worktreePath: z.string(),
      branch: z.string(),
      name: z.string(),
      createdAt: z.number().int().nonnegative(),
    })),
  }),
  z.object({ type: z.literal("repo:onboard:started"), repoPath: z.string() }),
  z.object({ type: z.literal("repo:onboard:output"), repoPath: z.string(), data: z.string() }),
  z.object({ type: z.literal("repo:onboard:complete"), repoPath: z.string(), success: z.boolean(), error: z.string().optional() }),
  z.object({ type: z.literal("repo:upgrade-specify:started"), repoPath: z.string() }),
  z.object({ type: z.literal("repo:upgrade-specify:output"), repoPath: z.string(), data: z.string() }),
  z.object({ type: z.literal("repo:upgrade-specify:complete"), repoPath: z.string(), success: z.boolean(), error: z.string().optional() }),
  z.object({ type: z.literal("repo:onboard:cancelled"), repoPath: z.string() }),
  z.object({ type: z.literal("repo:force-reload:started"), repoPath: z.string() }),
  z.object({ type: z.literal("job:started"), name: z.string() }),
  z.object({ type: z.literal("job:completed"), name: z.string(), elapsed: z.number() }),
  z.object({ type: z.literal("job:failed"), name: z.string(), error: z.string() }),
  z.object({ type: z.literal("git:user:result"), name: z.string(), email: z.string() }),
  z.object({
    type: z.literal("worktree:status:result"),
    worktreePath: z.string(),
    files: z.array(z.object({
      path: z.string(),
      status: z.enum(["added", "modified", "deleted", "renamed", "copied", "untracked"]),
    })),
    ahead: z.number().int().nonnegative(),
    behind: z.number().int().nonnegative(),
  }),
  z.object({
    type: z.literal("worktree:merge:result"),
    success: z.boolean(),
    message: z.string(),
  }),
  z.object({
    type: z.literal("worktree:branches:result"),
    repoPath: z.string(),
    branches: z.array(z.string()),
    current: z.string(),
  }),
  z.object({
    type: z.literal("worktree:delete:result"),
    success: z.boolean(),
    message: z.string(),
  }),
  z.object({ type: z.literal("terminal:spawned"), sessionId: z.string() }),
  z.object({ type: z.literal("terminal:input:ack") }),
  z.object({ type: z.literal("terminal:resize:ack") }),
  z.object({ type: z.literal("terminal:close:ack") }),
  z.object({ type: z.literal("terminal:data"), sessionId: z.string(), data: z.string() }),
  z.object({ type: z.literal("terminal:exited"), sessionId: z.string(), exitCode: z.number().int() }),
  z.object({ type: z.literal("ai-session:created"), session: AISessionRecordSchema }),
  z.object({ type: z.literal("ai-session:resumed"), session: AISessionRecordSchema }),
  z.object({ type: z.literal("ai-session:input:ack") }),
  z.object({ type: z.literal("ai-session:resize:ack") }),
  z.object({ type: z.literal("ai-session:stop:ack") }),
  z.object({ type: z.literal("ai-session:list:result"), sessions: z.array(AISessionRecordSchema) }),
  z.object({ type: z.literal("ai-session:deleted"), sessionId: z.string() }),
  z.object({ type: z.literal("ai-session:providers:result"), providers: z.record(z.enum(AI_PROVIDERS), ProviderMetaSchema) }),
  z.object({ type: z.literal("ai-session:data"), sessionId: z.string(), data: z.string() }),
  z.object({ type: z.literal("ai-session:status"), sessionId: z.string(), status: z.enum(AI_SESSION_STATUSES) }),
  z.object({ type: z.literal("ai-session:exited"), sessionId: z.string(), exitCode: z.number().int() }),
  z.object({ type: z.literal("ai-session:title"), sessionId: z.string(), title: z.string() }),
  z.object({ type: z.literal("error"), message: z.string() }),
]);

export type IpcRequest = z.infer<typeof IpcRequestSchema>;
export type IpcResponse = z.infer<typeof IpcResponseSchema>;
